name: CI

on:
  pull_request:
  push:
    branches:
      main

jobs:
  say_hello:
    name: "Say Hello"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello CI!"

  python_version:
    name: "Display the latest Python version. "
    runs-on: ubuntu-latest
    steps:
      - run: python --version
