name: CI

on:
  pull_request:
  push:
    branches:
      main

jobs:
  say_hello:
    name: "Say Hello"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello CI!"

  python_version:
    name: "Display the latest Python version. "
    runs-on: ubuntu-latest
    steps:
      - run: python --version

  run_specific_python:
    name: Run Python 3.13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python --version
